#Build Stage
FROM golang:1.22.4-alpine AS BuildStage

WORKDIR /app

# Copy the rest of the application code
COPY . ./

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
RUN go mod tidy


# Build the Go binary
RUN go build -o datetimeserver ./cmd/datetimehttp/main.go

EXPOSE 8090

#Deploy Stage
FROM alpine:latest AS datetimeserverhttp
WORKDIR /
COPY --from=BuildStage /app/datetimeserver /datetimeserver
EXPOSE 8090

ENTRYPOINT [ "/datetimeserver" ]